version: 2
enable-beta-ecosystems: true

updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"

    - package-ecosystem: "npm"
      directory: "/apps/commonality"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/apps/commonality/test/fixtures/empty-project"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/apps/commonality/test/fixtures/invalid-root-package"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/apps/commonality/test/fixtures/kitchen-sink-npm"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/apps/commonality/test/fixtures/kitchen-sink-npm/packages/pkg-one"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/apps/commonality/test/fixtures/kitchen-sink-yarn"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/apps/commonality/test/fixtures/kitchen-sink-yarn/packages/pkg-one"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/apps/commonality/test/fixtures/kitchen-sink"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/apps/commonality/test/fixtures/kitchen-sink/packages/pkg-one"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/apps/commonality/test/fixtures/missing-lockfile"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/apps/commonality/test/fixtures/with-configuration"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/apps/studio/fixtures/kitchen-sink-pnpm"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/apps/studio/fixtures/kitchen-sink-pnpm/packages/pkg-four"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/apps/studio/fixtures/kitchen-sink-pnpm/packages/pkg-one"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/apps/studio/fixtures/kitchen-sink-pnpm/packages/pkg-three"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/apps/studio/fixtures/kitchen-sink-pnpm/packages/pkg-two"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/apps/studio"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/apps/workshop"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/commonality-checks-recommended"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-codeowners"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-codeowners/test/fixtures/github-example"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-codeowners/test/fixtures/missing-file"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-codeowners/test/fixtures/simple/app/app-one"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-codeowners/test/fixtures/simple/packages/pkg-one"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-constraints"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-packages"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-packages/test/fixtures/kitchen-sink"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-packages/test/fixtures/kitchen-sink/packages/pkg-one"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-packages/test/fixtures/kitchen-sink/packages/pkg-two"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-packages/test/fixtures/missing-json-root/packages/pkg-one"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-packages/test/fixtures/missing-json"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-packages/test/fixtures/missing-lockfile"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-packages/test/fixtures/missing-lockfile/packages/pkg-one"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-packages/test/fixtures/missing-name-root"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-packages/test/fixtures/missing-name-root/packages/pkg-one"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-packages/test/fixtures/missing-name"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-packages/test/fixtures/missing-name/packages/pkg-one"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-packages/test/fixtures/single-package-repo"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-project"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-project/test/fixtures/deeply-nested/ignored-packages/pkg-three"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-project/test/fixtures/deeply-nested"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-project/test/fixtures/deeply-nested/packages/nested/pkg-two"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-project/test/fixtures/deeply-nested/packages/pkg-one"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-project/test/fixtures/missing-workspace-globs"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-project/test/fixtures/npm-workspace"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-project/test/fixtures/pnpm-workspace"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-project/test/fixtures/uninitialized"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-project/test/fixtures/yarn-workspace"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-tags"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-tags/test/fixtures/empty-project"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-tags/test/fixtures/empty-project/packages/pkg-one"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-tags/test/fixtures/empty-project/packages/pkg-three"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-tags/test/fixtures/empty-project/packages/pkg-two"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-tags/test/fixtures/kitchen-sink"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-tags/test/fixtures/kitchen-sink/packages/pkg-one"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-tags/test/fixtures/kitchen-sink/packages/pkg-three"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/data-tags/test/fixtures/kitchen-sink/packages/pkg-two"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/types"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/ui-conformance"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/ui-constraints"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/ui-core"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/ui-design-system"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/ui-graph"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/ui-package"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/utils-conformance"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/utils-core"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/utils-file"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/utils-onboarding"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/packages/utils-package"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/tooling/config-eslint"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/tooling/config-tailwind"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/tooling/config-tsconfig"
      schedule:
          interval: "daily"
      versioning-strategy: increase
