name: NPM

concurrency:
    group: NPM-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    security-events: write
    contents: write
    pull-requests: write

on:
    workflow_dispatch:
    release:
        types: [created]
    workflow_call:

jobs:
    Publish:
        runs-on: ubuntu-latest

        env:
            ADBLOCK: true
            ASTRO_TELEMETRY_DISABLED: 1
            AUTOMATEDLAB_TELEMETRY_OPTOUT: 1
            AZURE_CORE_COLLECT_TELEMETRY: 0
            CHOOSENIM_NO_ANALYTICS: 1
            DIEZ_DO_NOT_TRACK: 1
            DO_NOT_TRACK: 1
            DOTNET_CLI_TELEMETRY_OPTOUT: 1
            DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT: 1
            ET_NO_TELEMETRY: 1
            GATSBY_TELEMETRY_DISABLED: 1
            GATSBY_TELEMETRY_OPT_OUT: 1
            GATSBY_TELEMETRY_OPTOUT: 1
            GRIT_TELEMETRY_DISABLED: 1
            HASURA_GRAPHQL_ENABLE_TELEMETRY: false
            HINT_TELEMETRY: off
            HOMEBREW_NO_ANALYTICS: 1
            INFLUXD_REPORTING_DISABLED: true
            ITERATIVE_DO_NOT_TRACK: 1
            NEXT_TELEMETRY_DEBUG: 1
            NEXT_TELEMETRY_DISABLED: 1
            NG_CLI_ANALYTICS: false
            NUXT_TELEMETRY_DISABLED: 1
            PIN_DO_NOT_TRACK: 1
            POWERSHELL_TELEMETRY_OPTOUT: 1
            SAM_CLI_TELEMETRY: 0
            STNOUPGRADE: 1
            STRIPE_CLI_TELEMETRY_OPTOUT: 1
            TELEMETRY_DISABLED: 1
            TERRAFORM_TELEMETRY: 0
            VCPKG_DISABLE_METRICS: 1

        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4.2.2

            - uses: actions/setup-node@v4.3.0
              with:
                  node-version: "18"
                  registry-url: "https://registry.npmjs.org"

            - run: npm install -g npm

            - name: Publish ./apps/commonality
              continue-on-error: true
              working-directory: ./apps/commonality
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./apps/studio
              continue-on-error: true
              working-directory: ./apps/studio
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish .
              continue-on-error: true
              working-directory: .
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./packages/commonality-checks-recommended
              continue-on-error: true
              working-directory: ./packages/commonality-checks-recommended
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./packages/data-codeowners
              continue-on-error: true
              working-directory: ./packages/data-codeowners
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./packages/data-constraints
              continue-on-error: true
              working-directory: ./packages/data-constraints
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./packages/data-packages
              continue-on-error: true
              working-directory: ./packages/data-packages
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./packages/data-project
              continue-on-error: true
              working-directory: ./packages/data-project
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./packages/data-tags
              continue-on-error: true
              working-directory: ./packages/data-tags
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./packages/types
              continue-on-error: true
              working-directory: ./packages/types
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./packages/ui-conformance
              continue-on-error: true
              working-directory: ./packages/ui-conformance
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./packages/ui-constraints
              continue-on-error: true
              working-directory: ./packages/ui-constraints
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./packages/ui-core
              continue-on-error: true
              working-directory: ./packages/ui-core
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./packages/ui-design-system
              continue-on-error: true
              working-directory: ./packages/ui-design-system
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./packages/ui-graph
              continue-on-error: true
              working-directory: ./packages/ui-graph
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./packages/ui-package
              continue-on-error: true
              working-directory: ./packages/ui-package
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./packages/utils-conformance
              continue-on-error: true
              working-directory: ./packages/utils-conformance
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./packages/utils-core
              continue-on-error: true
              working-directory: ./packages/utils-core
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./packages/utils-file
              continue-on-error: true
              working-directory: ./packages/utils-file
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./packages/utils-onboarding
              continue-on-error: true
              working-directory: ./packages/utils-onboarding
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ./packages/utils-package
              continue-on-error: true
              working-directory: ./packages/utils-package
              run: |
                  npm publish --legacy-peer-deps --provenance --ignore-scripts
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
